@startuml

participant "<<class>>\n FileReaderWriter" as FRW
participant "<<class>>\n JsonExporter" as JE

-> FRW: saveMediTrackerData(path:Path)
activate FRW

FRW -> FRW: createTempSaveFile(jsonFolder:Path)
activate FRW
FRW --> FRW: tmpSaveFile:Path
deactivate FRW

FRW -> JE: saveMedicationDataToJson(tmpSaveFile:Path)
activate JE
JE -> JE: populateMedicationList()
activate JE
JE --> JE: medicationList:JSONArray
deactivate JE
JE->JE: writeJsonData(rootData:JSONObject, fileToWrite:Path)
activate JE
JE --> JE: :boolean
deactivate JE
JE --> FRW: saveStatus:boolean

deactivate JE
note over FRW
Checks status and renames the temp file
to the output file.
end note

<-- FRW
deactivate FRW

@enduml
