@startuml

actor User
title View Command Sequence Diagram
participant ":ViewCommand" as ViewCommand
participant ":ArgumentList" as ArgumentList
participant ":ArgumentParser" as ArgumentParser
participant "<<class>>\n MedicationManager" as MedicationManager
participant "<<class>>\n Ui" as Ui

User --> ViewCommand ** : new ViewCommand(args)
activate ViewCommand
ViewCommand -> ArgumentList: parse(args)

activate ArgumentList
ArgumentList -> ArgumentParser: parse(args)
deactivate ArgumentList

activate ArgumentParser
ArgumentParser --> ViewCommand: return parsedArgs
deactivate ArgumentParser

alt #transparent oneParsedArgs
    ViewCommand -> ViewCommand: execute(medication)
    activate ViewCommand #65c2a6

    ViewCommand -> MedicationManager: printSpecificMedication(medication)
    activate MedicationManager #d192d0
    MedicationManager -> MedicationManager: getMedication(medication)

    MedicationManager -> Ui: printSpecificMed(medicationDetails)
    activate Ui #c6d67e
    Ui --[#red]> MedicationManager: <font color=red><b>return
    MedicationManager --[#red]> ViewCommand: <font color=red><b>return
    deactivate MedicationManager

    ViewCommand -> Ui: showSuccessMessage("Medication details has been retrieved")
    Ui --[#red]> ViewCommand: <font color=red><b>return
    deactivate Ui

else #transparent more\nThanOne\nParsed\nArgs
    ViewCommand -> Ui: showErrorMessage("You can only have one flag!")
    activate Ui #c6d67e
    Ui --[#blue]> ViewCommand: <font color=blue><b>return
    deactivate Ui
end

deactivate ViewCommand
User <-- ViewCommand
deactivate ViewCommand

@enduml