@startuml

actor User #e67678
title View Command Sequence Diagram
participant ":ViewCommand" as ViewCommand
participant "ARGUMENT_LIST:ArgumentList" as ArgumentList
participant ":ArgumentParser" as ArgumentParser
participant ":ArgumentName" as ArgumentName
participant "<<class>>\n MedicationManager" as MedicationManager
participant "<<class>>\n Ui" as Ui

User --> ViewCommand ** : new ViewCommand(argument)
activate ViewCommand
ViewCommand -> ArgumentList: parse(argument)
activate ArgumentList #e67678
ArgumentList -> ArgumentParser ** : New ArgumentParser(argument)
activate ArgumentParser #a67671
ArgumentParser --[#red]> ArgumentList: parsedArguments
deactivate ArgumentParser
ArgumentList --[#red]> ViewCommand: parsedArguments
deactivate ArgumentList

ViewCommand -> ViewCommand: <font color=blue> execute(medication)
activate ViewCommand #65c2a6

    alt oneParsedArgument
        ViewCommand -> MedicationManager: printSpecificMedication(medication)
        activate MedicationManager #d192d0
        MedicationManager -> MedicationManager: getMedication(medication)

        MedicationManager -> Ui: <font color=blue> printSpecificMed(medicationDetails)
        activate Ui #c6d67e
        Ui --[#red]> MedicationManager: <font color=red>
        MedicationManager --[#red]> ViewCommand: <font color=red>
        deactivate MedicationManager

        ViewCommand -> Ui: showSuccessMessage("Medication details has been retrieved")
        Ui --[#red]> ViewCommand: <font color=red>
        deactivate Ui

    else #transparent more\nThanOne\nParsed\nArgs
        ViewCommand -> Ui: showErrorMessage("You can only have one flag!")
        activate Ui #c6d67e
        Ui --[#red]> ViewCommand: <font color=red>
        deactivate Ui
    end

ViewCommand --[#blue]> ViewCommand
deactivate ViewCommand
User <[#red]-- ViewCommand
deactivate ViewCommand

@enduml